-- =====================================================================
-- AS-SUNNAH FOUNDATION TRACKER: MASTER DATABASE RESET & HARDENING
-- Version: 2.0 (FINAL)
-- Purpose: Complete reset, solving recursion, and industrial security.
-- =====================================================================

-- ── 1. CLEAN SLATE (DROP EVERYTHING) ────────────────────────────────
-- This removes all existing tables, types, and functions to ensure no conflicts.
DROP VIEW IF EXISTS public.view_department_analytics;
DROP TABLE IF EXISTS public.daily_logs;
DROP TABLE IF EXISTS public.amal_tasks;
DROP TABLE IF EXISTS public.profiles;
DROP TYPE IF EXISTS employee_role;
DROP FUNCTION IF EXISTS public.check_is_admin;
DROP FUNCTION IF EXISTS public.is_admin;
DROP FUNCTION IF EXISTS public.update_timestamp;

-- ── 2. CORE TYPES & EXTENSIONS ──────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE employee_role AS ENUM ('employee', 'admin', 'manager');

-- ── 3. RECURSION-PROOF SECURITY HELPERS ─────────────────────────────
-- This function is the key to fixing the "Infinite Recursion" error.
-- SECURITY DEFINER runs with superuser power, bypassing RLS to check roles.
CREATE OR REPLACE FUNCTION public.check_is_admin() 
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() 
    AND (role = 'admin' OR role = 'manager')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ── 4. TABLES DEFINITION ────────────────────────────────────────────

-- PROFILES: Source of truth for identity
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  department TEXT NOT NULL DEFAULT 'General',
  employee_id TEXT UNIQUE NOT NULL,
  sub_institute TEXT DEFAULT 'Main Branch',
  role employee_role DEFAULT 'employee',
  is_profile_complete BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- DAILY LOGS: Spiritual tracking data
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  completion_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- AMAL TASKS: Global task definitions
CREATE TABLE public.amal_tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT NOT NULL,
  input_type TEXT NOT NULL DEFAULT 'checkbox',
  points INTEGER DEFAULT 1,
  frequency TEXT DEFAULT 'daily',
  active_days INTEGER[],
  icon_code TEXT,
  color_value BIGINT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 5. PERFORMANCE INDEXES ─────────────────────────────────────────
CREATE INDEX idx_profiles_role ON public.profiles(role);
CREATE INDEX idx_logs_user_date ON public.daily_logs (user_id, date);
CREATE INDEX idx_logs_completion ON public.daily_logs USING gin(completion_data);

-- ── 6. ROW LEVEL SECURITY (RLS) ───────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amal_tasks ENABLE ROW LEVEL SECURITY;

-- 🟢 PROFILE POLICIES (Recursion-Free)
CREATE POLICY "profiles_select_policy" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR check_is_admin());

CREATE POLICY "profiles_insert_policy" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "profiles_update_policy" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- 🔵 DAILY LOGS POLICIES
CREATE POLICY "logs_owner_policy" ON public.daily_logs
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "logs_admin_policy" ON public.daily_logs
  FOR SELECT USING (check_is_admin());

-- 🟠 AMAL TASKS POLICIES
CREATE POLICY "tasks_view_policy" ON public.amal_tasks
  FOR SELECT TO authenticated USING (is_active = true);

CREATE POLICY "tasks_admin_policy" ON public.amal_tasks
  FOR ALL TO authenticated USING (check_is_admin());

-- ── 7. AUTOMATION (TRIGGERS) ──────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_profile_time BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_timestamp();
CREATE TRIGGER tr_update_logs_time BEFORE UPDATE ON public.daily_logs FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ── 8. SEED DATA (Institutional Standards) ────────────────────────
INSERT INTO public.amal_tasks (id, title, subtitle, category, points, frequency, icon_code, color_value) VALUES
('morning_adhkar', 'Morning Adhkar', 'Complete before sunrise', 'spiritual', 3, 'daily', '984365', 4282501089),
('evening_adhkar', 'Evening Adhkar', 'Complete before maghrib', 'spiritual', 3, 'daily', '984365', 4294939392),
('office_cleanliness', 'Workspace Cleanliness', 'Maintain a professional desk', 'professional', 2, 'daily', '984401', 4280523008),
('fajr_jamaat', 'Fajr with Jamaat', 'Pray at the Masjid', 'prayer', 5, 'daily', '984384', 4280172783)
ON CONFLICT (id) DO NOTHING;
