-- =====================================================================
-- AS-SUNNAH FOUNDATION TRACKER: MASTER DATABASE RESET & HARDENING
-- Version: 2.1 (ULTIMATE)
-- Purpose: Complete reset, solving recursion, and ensuring analytical parity.
-- =====================================================================

-- ── 1. CLEAN SLATE (DROP EVERYTHING) ────────────────────────────────
-- This removes all existing objects to ensure a perfect 1-to-1 sync with the app logic.
DROP VIEW IF EXISTS public.view_department_analytics;
DROP TABLE IF EXISTS public.announcements;
DROP TABLE IF EXISTS public.daily_logs;
DROP TABLE IF EXISTS public.amal_tasks;
DROP TABLE IF EXISTS public.profiles;
DROP TYPE IF EXISTS employee_role;
DROP FUNCTION IF EXISTS public.check_is_admin;
DROP FUNCTION IF EXISTS public.update_timestamp;

-- ── 2. CORE TYPES & EXTENSIONS ──────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TYPE employee_role AS ENUM ('employee', 'admin', 'manager');

-- ── 3. RECURSION-PROOF SECURITY HELPERS ─────────────────────────────
-- SECURITY DEFINER runs with superuser power, bypassing RLS to check roles.
-- SET search_path = public is a security best practice to prevent search-path injection.
CREATE OR REPLACE FUNCTION public.check_is_admin() 
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() 
    AND (role = 'admin' OR role = 'manager')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ── 4. TABLES DEFINITION ────────────────────────────────────────────

-- PROFILES: Source of truth for institutional identity
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  department TEXT NOT NULL DEFAULT 'General',
  employee_id TEXT UNIQUE NOT NULL,
  sub_institute TEXT DEFAULT 'Main Branch',
  role employee_role DEFAULT 'employee',
  is_profile_complete BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AMAL TASKS: Institutional task definitions with rich UI metadata
CREATE TABLE public.amal_tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT NOT NULL,
  input_type TEXT NOT NULL DEFAULT 'checkbox',
  points INTEGER DEFAULT 1,
  frequency TEXT DEFAULT 'daily',
  active_days INTEGER[],
  icon_code TEXT,
  color_value BIGINT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DAILY LOGS: Spiritual performance data
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  completion_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- ANNOUNCEMENTS: Institutional communication bridge
CREATE TABLE public.announcements (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES public.profiles(id)
);

-- ── 5. PERFORMANCE & ANALYTICS ─────────────────────────────────────

-- Optimized View for Admin Dashboard Reports
CREATE OR REPLACE VIEW public.view_department_analytics AS
SELECT 
    p.department,
    p.sub_institute,
    COUNT(DISTINCT p.id) as total_employees,
    COUNT(l.id) as total_logs_filled,
    DATE_TRUNC('month', l.date) as log_month
FROM public.profiles p
LEFT JOIN public.daily_logs l ON p.id = l.user_id
GROUP BY p.department, p.sub_institute, DATE_TRUNC('month', l.date);

-- Global indexing for high-concurrency scaling
CREATE INDEX idx_profiles_role ON public.profiles(role);
CREATE INDEX idx_logs_user_date ON public.daily_logs (user_id, date);
CREATE INDEX idx_logs_completion ON public.daily_logs USING gin(completion_data);

-- ── 6. ROW LEVEL SECURITY (RLS) ───────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 🟢 PROFILES: Recursion-Free Policies
CREATE POLICY "profiles_read_all" ON public.profiles FOR SELECT USING (auth.uid() = id OR check_is_admin());
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 🔵 DAILY LOGS: Privacy & Oversight
CREATE POLICY "logs_owner_access" ON public.daily_logs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "logs_admin_read" ON public.daily_logs FOR SELECT USING (check_is_admin());

-- 🟠 AMAL TASKS: Controlled Distribution
CREATE POLICY "tasks_read_public" ON public.amal_tasks FOR SELECT TO authenticated USING (is_active = true);
CREATE POLICY "tasks_manage_admin" ON public.amal_tasks FOR ALL TO authenticated USING (check_is_admin());

-- 🟣 ANNOUNCEMENTS: Communication Loop
CREATE POLICY "announcements_read_all" ON public.announcements FOR SELECT TO authenticated USING (true);
CREATE POLICY "announcements_manage_admin" ON public.announcements FOR ALL USING (check_is_admin());

-- ── 7. AUTOMATION (TRIGGERS) ──────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_profile_time BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_timestamp();
CREATE TRIGGER tr_update_logs_time BEFORE UPDATE ON public.daily_logs FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ── 8. SEED DATA (Foundation Essentials) ──────────────────────────
INSERT INTO public.amal_tasks (id, title, subtitle, category, points, frequency, icon_code, color_value) VALUES
('morning_adhkar', 'Morning Adhkar', 'Complete before sunrise', 'spiritual', 3, 'daily', '984365', 4282501089),
('evening_adhkar', 'Evening Adhkar', 'Complete before maghrib', 'spiritual', 3, 'daily', '984365', 4294939392),
('office_cleanliness', 'Workspace Cleanliness', 'Maintain a professional desk', 'professional', 2, 'daily', '984401', 4280523008),
('fajr_jamaat', 'Fajr with Jamaat', 'Pray at the Masjid', 'prayer', 5, 'daily', '984384', 4280172783)
ON CONFLICT (id) DO NOTHING;

-- Grant permissions to authenticated users
GRANT SELECT ON public.view_department_analytics TO authenticated;
