name: Bug Report
description: Create a technical report to identify system defects.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide a detailed report to assist in the identification and resolution of the defect.
  - type: textarea
    id: defect-description
    attributes:
      label: Defect Description
      description: Provide a clear and concise description of the observed behavior.
      placeholder: Describe the defect.
    validations:
      required: true
  - type: dropdown
    id: application-target
    attributes:
      label: Application Target
      description: Identify the application environment where the defect occurred.
      options:
        - Amal Tracker (Client)
        - Foundation Admin
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide the exact steps required to reproduce the observed behavior.
      placeholder: |
        1. Navigate to '...'
        2. Execute '....'
        3. Observe '....'
    validations:
      required: true
  - type: input
    id: environment-info
    attributes:
      label: Environment Information
      description: Provide the result of `flutter --version` and the device model.
  - type: textarea
    id: logs
    attributes:
      label: System Logs
      description: Provide relevant log output from the debugger or device console.
      render: shell
