-- =====================================================================
-- AS-SUNNAH FOUNDATION TRACKER: ENTERPRISE DATABASE SCHEMA
-- Version: 1.1
-- Purpose: Optimized for institutional scaling and department analytics
-- =====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. ENUMS & DOMAINS
CREATE TYPE employee_role AS ENUM ('employee', 'admin', 'manager');

-- 3. PROFILES (Institutional Metadata)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  department TEXT NOT NULL DEFAULT 'General',
  employee_id TEXT UNIQUE NOT NULL,
  sub_institute TEXT DEFAULT 'Main Branch',
  role employee_role DEFAULT 'employee',
  is_profile_complete BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. DAILY LOGS (Tracking Data)
CREATE TABLE IF NOT EXISTS public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  values JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

CREATE INDEX idx_logs_user_date ON public.daily_logs (user_id, date);
CREATE INDEX idx_logs_date ON public.daily_logs (date);

-- 5. ANALYTICS VIEWS
-- Provides aggregated department performance for the Admin Panel
CREATE OR REPLACE VIEW public.view_department_analytics AS
SELECT 
    p.department,
    p.sub_institute,
    COUNT(DISTINCT p.id) as total_employees,
    COUNT(l.id) as total_logs_filled,
    DATE_TRUNC('month', l.date) as log_month
FROM public.profiles p
LEFT JOIN public.daily_logs l ON p.id = l.user_id
GROUP BY p.department, p.sub_institute, DATE_TRUNC('month', l.date);

-- 6. SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;

-- Profiles: Own view or Admin view
CREATE POLICY "Profiles are viewable by owner or admin" ON public.profiles
FOR SELECT USING (
  auth.uid() = id OR 
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'manager')
);

-- Logs: Own management or Admin oversight
CREATE POLICY "Logs are manageable by owner" ON public.daily_logs
FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Admins can oversee all logs" ON public.daily_logs
FOR SELECT USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'manager')
);

-- 7. TRIGGERS (Automated Sync)
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_profile_time BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_timestamp();
CREATE TRIGGER tr_update_logs_time BEFORE UPDATE ON public.daily_logs FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- 8. INITIAL SEED DATA (Standard Tasks)
CREATE TABLE IF NOT EXISTS public.amal_tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  input_type TEXT NOT NULL DEFAULT 'checkbox',
  points INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.amal_tasks (id, title, category, points) VALUES
('fajr_jamaat', 'Fajr with Jama''at', 'salah', 5),
('dhuhr_jamaat', 'Dhuhr with Jama''at', 'salah', 5),
('asr_jamaat', 'Asr with Jama''at', 'salah', 5),
('maghrib_jamaat', 'Maghrib with Jama''at', 'salah', 5),
('isha_jamaat', 'Isha with Jama''at', 'salah', 5)
ON CONFLICT (id) DO NOTHING;
